name: Deploy new schema to other repos

env:
  USERNAME: ${{ github.actor }}
  ADDRESS_SUFFIX: users.noreply.github.com
  THE_SERVER: ${{ github.server_url }}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:

  push:
    branches:
      - 'main'
    paths:
      - 'mongodb/schema.prisma'

jobs:
  update-schema-mongodb:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        repositories: [cadastro-msr]
    steps:
      - name: Checkout current repository
        uses: actions/checkout@v3

      - name: Checkout lambda-pedido-acolhimento
        uses: actions/checkout@v3
        with:
          repository: mapadoacolhimento/${{ matrix.repositories }}
          ref: 'main'
          path: ${{ matrix.repositories }}
          token: ${{ secrets.ACTIONS_GITHUB_TOKEN }}

      - name: Update schema file
        working-directory: ${{ matrix.repositories }}
        run: |
          rm ./prisma/mongodb/schema.prisma
          cp -u ../mongodb/schema.prisma ./prisma/mongodb

      - name: Check for changes
        working-directory: ${{ matrix.repositories }}
        run: |
          if git diff --quiet; then
            echo "No changes detected. Exiting."
            echo "exiting=true" >> $GITHUB_ENV
          fi

      - name: Commit changes
        if: env.exiting != 'true'
        working-directory: ${{ matrix.repositories }}
        run: |
          git config user.name "$USERNAME"
          git config user.email "$USERNAME@$ADDRESS_SUFFIX"
          git add prisma/mongodb/schema.prisma
          git commit -m "feat: updated mongodb/schema.prisma file from $THE_SERVER/mapadoacolhimento/mapa-migrations/blob/main/mongodb/schema.prisma"

      - name: Push to main
        if: env.exiting != 'true'
        working-directory: ${{ matrix.repositories }}
        run: git push origin main
