name: Deploy new schema to other repos

env:
  USERNAME: ${{ github.actor }}
  ADDRESS_SUFFIX: users.noreply.github.com
  THE_SERVER: ${{ github.server_url }}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - 'main'
    paths:
      - 'schema.prisma'

jobs:
  update-schema:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current repository
        uses: actions/checkout@v3

      - name: Checkout lambda-pedido-acolhimento
        uses: actions/checkout@v3
        with:
          repository: 'mapadoacolhimento/lambda-pedido-acolhimento'
          ref: 'main'
          path: 'lambda-pedido-acolhimento'
          token: ${{ secrets.ACTIONS_GITHUB_TOKEN }}

      - name: Update schema file
        working-directory: lambda-pedido-acolhimento
        run: |
          rm ./prisma/schema.prisma
          cp -u ../schema.prisma ./prisma

      - name: Check for changes
        working-directory: lambda-pedido-acolhimento
        run: |
          if git diff --quiet; then
            echo "No changes detected. Exiting."
            echo "exiting=true" >> $GITHUB_ENV
          fi

      - name: Commit changes
        if: env.exiting != 'true'
        working-directory: lambda-pedido-acolhimento
        run: |
          git config user.name "$USERNAME"
          git config user.email "$USERNAME@$ADDRESS_SUFFIX"
          git add prisma/schema.prisma
          git commit -m "feat: updated schema.prisma file from $THE_SERVER/mapadoacolhimento/mapa-migrations/blob/main/schema.prisma"

      - name: Push to main
        if: env.exiting != 'true'
        working-directory: lambda-pedido-acolhimento
        run: git push origin main
